package com.allperiph.ui

import android.Manifest
import android.animation.ValueAnimator
import android.app.Activity
import android.app.AlertDialog
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.content.res.Configuration
import android.graphics.RectF
import android.graphics.Typeface
import android.graphics.drawable.GradientDrawable
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.provider.Settings
import android.view.Gravity
import android.view.LayoutInflater
import android.view.MotionEvent
import android.view.View
import android.view.WindowInsets
import android.view.WindowInsetsController
import android.view.animation.DecelerateInterpolator
import android.view.animation.OvershootInterpolator
import android.widget.Button
import android.widget.EditText
import android.widget.FrameLayout
import android.widget.ImageView
import android.widget.LinearLayout
import android.widget.Switch
import android.widget.TextView
import android.widget.ViewFlipper
import kotlin.math.abs
import kotli.core.bindView
import android.view.View.MeasureSpec
import android.widget.PopupWindow
import android.graphics.Color
import android.text.SpannableStringBuilder
import android.text.style.ForegroundColorSpan
import android.text.SpannableString
import android.text.Spannable
import android.text.style.StyleSpan
import android.graphics.fonts.FontFamily
import android.util.DisplayMetrics
import android.view.WindowManager
import android.view.ViewTreeObserver
import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.Path
import android.graphics.PathMeasure
import android.graphics.LinearGradient
import android.graphics.Shader
import android.graphics.CornerPathEffect
import android.animation.ObjectAnimator
import android.view.animation.AccelerateDecelerateInterpolator
import android.view.animation.LinearInterpolator
import android.view.animation.PathInterpolator
import android.graphics.PointF
import android.graphics.Rect
import android.graphics.BlurMaskFilter
import android.graphics.PorterDuff
import android.graphics.PorterDuffXfermode
import android.graphics.Xfermode
import android.graphics.PorterDuffXfermode
import android.widget.FrameLayout.LayoutParams
import android.view.View.OnTouchListener
import android.view.animation.AnimationUtils
import android.view.animation.Animation
import android.view.animation.TranslateAnimation
import android.view.animation.AlphaAnimation
import android.view.animation.ScaleAnimation
import android.view.animation.RotateAnimation
import android.view.animation.AnimationSet
import android.view.animation.Interpolator
import android.view.animation.LinearOutSlowInInterpolator
import android.view.animation.OvershootInterpolator
import android.view.animation.BounceInterpolator
import android.view.animation.PathInterpolator
import android.view.animation.AccelerateInterpolator
import android.view.animation.DecelerateInterpolator
import android.view.animation.AccelerateDecelerateInterpolator
import android.view.animation.CycleInterpolator
import android.view.animation.UndecelerateInterpolator
import android.view.animation.AnticipateInterpolator
import android.view.animation.AnticipateOvershootInterpolator
import android.view.animation.BackInterpolator
import android.view.animation.BounceInterpolator
import android.view.animation.ElasticInterpolator
import android.view.animation.ExpoInterpolator
import android.view.animation.CircleInterpolator
import android.view.animation.SineInterpolator
import android.view.animation.CubicBezierInterpolator
import android.view.animation.SplineInterpolator
import android.view.animation.LookupTableInterpolator
import android.view.animation.Interpolator
import android.view.animation.Animation
import android.view.animation.AnimationSet
import android.view.animation.AnimationUtils
import android.view.animation.LayoutAnimationController
import android.view.animation.AnimationDescription
import android.view.animation.LayoutAnimation
import android.view.animation.GridLayoutAnimationController
import android.view.animation.AlphaAnimation
import android.view.animation.ScaleAnimation
import android.view.animation.TranslateAnimation
import android.view.animation.RotateAnimation
import android.view.animation.AnimationSet
import android.view.animation.DecelerateInterpolator
import android.view.animation.AccelerateInterpolator
import android.view.animation.LinearInterpolator
import android.view.animation.OvershootInterpolator
import android.view.animation.BounceInterpolator
import android.view.animation.AnticipateInterpolator
import android.view.animation.AnticipateOvershootInterpolator
import android.view.animation.AccelerateDecelerateInterpolator
import android.view.animation.CycleInterpolator
import android.view.animation.UndecelerateInterpolator
import android.view.animation.BackInterpolator
import android.view.animation.ElasticInterpolator
import android.view.animation.ExpoInterpolator
import android.view.animation.CircleInterpolator
import android.view.animation.SineInterpolator
import android.view.animation.CubicBezierInterpolator
import android.view.animation.SplineInterpolator
import android.view.animation.LookupTableInterpolator
import android.view.animation.Interpolator
import android.view.animation.Animation
import android.view.animation.AnimationSet
import android.view.animation.AnimationUtils
import android.view.animation.LayoutAnimationController
import android.view.animation.AnimationDescription
import android.view.animation.LayoutAnimation
import android.view.animation.GridLayoutAnimationController
import android.view.animation.AlphaAnimation
import android.view.animation.ScaleAnimation
import android.view.animation.TranslateAnimation
import android.view.animation.RotateAnimation
import android.view.animation.AnimationSet
import android.view.animation.DecelerateInterpolator
import android.view.animation.AccelerateInterpolator
import android.view.animation.LinearInterpolator
import android.view.animation.OvershootInterpolator
import android.view.animation.BounceInterpolator
import android.view.animation.AnticipateInterpolator
import android.view.animation.AnticipateOvershootInterpolator
import android.view.animation.AccelerateDecelerateInterpolator
import android.view.animation.CycleInterpolator
import android.view.animation.UndecelerateInterpolator
import android.view.animation.BackInterpolator
import android.view.animation.ElasticInterpolator
import android.view.animation.ExpoInterpolator
import android.view.animation.CircleInterpolator
import android.view.animation.SineInterpolator
import android.view.animation.CubicBezierInterpolator
import android.view.animation.SplineInterpolator
import android.view.animation.LookupTableInterpolator
import android.view.animation.Interpolator
import android.view.animation.Animation
import android.view.animation.AnimationSet
import android.view.animation.AnimationUtils
import android.view.animation.LayoutAnimationController
import android.view.animation.AnimationDescription
import android.view.animation.LayoutAnimation
import android.view.animation.GridLayoutAnimationController
import android.view.animation.AlphaAnimation
import android.view.animation.ScaleAnimation
import android.view.animation.TranslateAnimation
import android.view.animation.RotateAnimation
import android.view.animation.AnimationSet
import android.view.animation.DecelerateInterpolator
import android.view.animation.AccelerateInterpolator
import android.view.animation.LinearInterpolator
import android.view.animation.OvershootInterpolator
import android.view.animation.BounceInterpolator
import android.view.animation.AnticipateInterpolator
import android.view.animation.AnticipateOvershootInterpolator
import android.view.animation.AccelerateDecelerateInterpolator
import android.view.animation.CycleInterpolator
import android.view.animation.UndecelerateInterpolator
import android.view.animation.BackInterpolator
import android.view.animation.ElasticInterpolator
import android.view.animation.ExpoInterpolator
import android.view.animation.CircleInterpolator
import android.view.animation.SineInterpolator
import android.view.animation.CubicBezierInterpolator
import android.view.animation.SplineInterpolator
import android.view.animation.LookupTableInterpolator
import android.view.animation.Interpolator
import android.view.animation.Animation
import android.view.animation.AnimationSet
import android.view.animation.AnimationUtils
import android.view.animation.LayoutAnimationController
import android.view.animation.AnimationDescription
import android.view.animation.LayoutAnimation
import android.view.animation.GridLayoutAnimationController
import android.view.animation.AlphaAnimation
import android.view.animation.ScaleAnimation
import android.view.animation.TranslateAnimation
import android.view.animation.RotateAnimation
import android.view.animation.AnimationSet
import android.view.animation.DecelerateInterpolator
import android.view.animation.AccelerateInterpolator
import android.view.animation.LinearInterpolator
import android.view.animation.OvershootInterpolator
import android.view.animation.BounceInterpolator
import android.view.animation.AnticipateInterpolator
import android.view.animation.AnticipateOvershootInterpolator
import android.view.animation.AccelerateDecelerateInterpolator
import android.view.animation.CycleInterpolator
import android.view.animation.UndecelerateInterpolator
import android.view.animation.BackInterpolator
import android.view.animation.ElasticInterpolator
import android.view.animation.ExpoInterpolator
import android.view.animation.CircleInterpolator
import android.view.animation.SineInterpolator
import android.view.animation.CubicBezierInterpolator
import android.view.animation.SplineInterpolator
import android.view.animation.LookupTableInterpolator
import android.view.animation.Interpolator
import android.view.animation.Animation
import android.view.animation.AnimationSet
import android.view.animation.AnimationUtils
import android.view.animation.LayoutAnimationController
import android.view.animation.AnimationDescription
import android.view.animation.LayoutAnimation
import android.view.animation.GridLayoutAnimationController
import android.view.animation.AlphaAnimation
import android.view.animation.ScaleAnimation
import android.view.animation.TranslateAnimation
import android.view.animation.RotateAnimation
import android.view.animation.AnimationSet
import android.view.animation.DecelerateInterpolator
import android.view.animation.AccelerateInterpolator
import android.view.animation.LinearInterpolator
import android.view.animation.OvershootInterpolator
import android.view.animation.BounceInterpolator
import android.view.animation.AnticipateInterpolator
import android.view.animation.AnticipateOvershootInterpolator
import android.view.animation.AccelerateDecelerateInterpolator
import android.view.animation.CycleInterpolator
import android.view.animation.UndecelerateInterpolator
import android.view.animation.BackInterpolator
import android.view.animation.ElasticInterpolator
import android.view.animation.ExpoInterpolator
import android.view.animation.CircleInterpolator
import android.view.animation.SineInterpolator
import android.view.animation.CubicBezierInterpolator
import android.view.animation.SplineInterpolator
import android.view.animation.LookupTableInterpolator
import android.view.animation.Interpolator